# Generated by Django 5.2.1 on 2025-05-10 00:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lession',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
